### PR TITLE
lesslol/JadeCore548-patched

### PR DESCRIPTION
**Pull request by Exodius**

### CODE REVIEW

**Comment by edgarchiroleo** [comment]
Hello, I have downloaded the repository of this project to prove it, I know a little programming, although I have always developed with C # and other languages but very little with C ++, at the moment what most hits me is the structure of the project and its Workflow. For example I would like to be able to follow the workflow of a spell launched by the warlock, as it is calculated its cooldown, base damage and also cast to the target and do it damage on him. Please give me some clue how to start studying the workflow, to be able to help in the project. Thank you

**Comment by Exodius** [comment]
Thanks for the comment but, I am afraid that I won't be much of a help.  I don't know C++ and I have worked only with SQL. The repositories stored on my account are there, mainly, for archiving purpose. I don't have a clue if some (or any) of them are working or not. They are present because something among all this hectic junk, someone can find something useful that can be used as a basic framework that can be improved. I am {or better '_I was_') a contributor for project @TrinityCore from which this and many other forks/projects derived... If you are interested in helping out a project that has a steady flow of development, please check @TrinityCore and start there. If you do decide to stick around and help TC, I'll be looking forward to see your work there...

Cheers :)

**Comment by edgarchiroleo** [comment]
Thank you for your response, I will seek help in the trinity project. But I'm more interested in the MOP project and now trinity is passing its project to Legion, because here we have a LAN where we play the MOP version of WOW, and we want to go fix the problems of the spell, I have been in for a very short time In the structure of the project, and I still have some doubts, as I have experience as a programmer, project structures can be complicated if there is no document to be documented. Thanks again. Best Regards

**Comment by Exodius** [comment]
That's why I suggested Trinity. Yes, they have advanced to develop Legion but, unlike most of other projects, their core is fairly documented and if you get stuck somewhere, people will help you out on either forums or IRC...

**Pull request merged**
